version: "3"
services:
  share_traffic:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
    image: "harleyliu/share_traffic:latest"
    build: .
    tty: true
    privileged: true
    ports:
      - $MESON_PORT:$MESON_PORT
      - $SUPERVISOR_PROT:9001
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DEVICE_NAME=$DEVICE_NAME
      - EARNAPP_UUID=$EARNAPP_DEVICE_ID
      - EARNFM_TOKEN=$EARNFM_TOKEN
      - GAGANODE_TOKEN=$GAGANODE_TOKEN
      - HONEYGAIN_EMAIL=$HONEYGAIN_EMAIL
      - HONEYGAIN_PASSWD=$HONEYGAIN_PASSWD
      - IPROYALPAWNS_EMAIL=$IPROYALPAWNS_EMAIL
      - IPROYALPAWNS_PASSWD=$IPROYALPAWNS_PASSWD
      - MESON_TOKEN=$MESON_TOKEN
      - MESON_PORT=$MESON_PORT
      - CID=$PACKETSTREAM_CID
      - PEER2PROFIT_EMAIL=$PEER2PROFIT_EMAIL
      - PROXYLITE_USER_ID=$PROXYLITE_USER_ID
      - PROXYRACK_UUID=$PROXYRACK_UUID
      - SPEEDSHARE_TOKEN=$SPEEDSHARE_TOKEN
    volumes:
      - ./data/bitping:/root/.bitping
    network_mode: service:tun2socks

  adnade:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
    image: harleyliu/adnade:latest
    restart: always
    environment:
      - ADNADE_USERNAME=$ADNADE_USERNAME
      - PROXY_LIST=$ADNADE_PROXY_LIST
      - PROXY_AUTH_LIST=$ADNADE_PROXY_AUTH_LIST
    volumes:
      - ./data/adnade:/app/screenshot
    network_mode: service:tun2socks

  grass:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
    image: mrcolorrain/grass
    restart: always
    hostname: $DEVICE_NAME
    environment:
      - GRASS_USER=$GRASS_USER
      - GRASS_PASS=$GRASS_PASS
    network_mode: service:tun2socks

  Repocket:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    image: repocket/repocket:latest
    restart: always
    environment:
      - RP_EMAIL=$REPOCKET_EMAIL
      - RP_API_KEY=$REPOCKET_API_KEY
    network_mode: service:tun2socks

  TraffMonetizer:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    image: traffmonetizer/cli_v2:latest
    restart: always
    command: start accept --token ${TRAFFMONETIZER_TOKEN}
    network_mode: service:tun2socks

  dockerUI:
    image: joinsunsoft/docker.ui:latest
    restart: always
    ports:
      - 8999:8999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: service:tun2socks

  tun2socks:
      image: xjasonlyu/tun2socks
      restart: always
      command: ["/bin/sh", "-c", "echo 'nameserver 1.1.1.1\nnameserver 8.8.8.8' > /etc/resolv.conf && ip rule add iif lo ipproto udp dport 53 lookup main && ip rule add iif lo ipproto udp dport 3478 lookup main"]
      environment:
          - LOGLEVEL=info
          - PROXY=$PROXY
      volumes:
          - '/dev/net/tun:/dev/net/tun'
      cap_add:
          - NET_ADMIN
