version: "3"
services:
  share_traffic:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
    image: "harleyliu/share_traffic:latest"
    build: .
    tty: true
    privileged: true
    ports:
      - $MESON_PORT:$MESON_PORT
      - $SUPERVISOR_PROT:9001
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DEVICE_NAME=$DEVICE_NAME
      - EARNAPP_UUID=$EARNAPP_DEVICE_ID
      - EARNFM_TOKEN=$EARNFM_TOKEN
      - GAGANODE_TOKEN=$GAGANODE_TOKEN
      - HONEYGAIN_EMAIL=$HONEYGAIN_EMAIL
      - HONEYGAIN_PASSWD=$HONEYGAIN_PASSWD
      - IPROYALPAWNS_EMAIL=$IPROYALPAWNS_EMAIL
      - IPROYALPAWNS_PASSWD=$IPROYALPAWNS_PASSWD
      - MESON_TOKEN=$MESON_TOKEN
      - MESON_PORT=$MESON_PORT
      - CID=$PACKETSTREAM_CID
      - PEER2PROFIT_EMAIL=$PEER2PROFIT_EMAIL
      - PROXYLITE_USER_ID=$PROXYLITE_USER_ID
      - PROXYRACK_UUID=$PROXYRACK_UUID
      - SPEEDSHARE_TOKEN=$SPEEDSHARE_TOKEN
    volumes:
      - ./data/bitpingd:/root/.bitpingd
    networks:
      share_traffic:
        ipv4_address: 172.106.0.10

  adnade:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
    image: harleyliu/adnade:latest
    restart: always
    environment:
      - ADNADE_USERNAME=$ADNADE_USERNAME
      - PROXY_LIST=$ADNADE_PROXY_LIST
      - PROXY_AUTH_LIST=$ADNADE_PROXY_AUTH_LIST
    networks:
      share_traffic:
        ipv4_address: 172.106.0.20

  grass:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
    image: mrcolorrain/grass
    restart: always
    hostname: $DEVICE_NAME
    environment:
      - GRASS_USER=$GRASS_USER
      - GRASS_PASS=$GRASS_PASS
    networks:
      share_traffic:
        ipv4_address: 172.106.0.30

  # mysterium:
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 100M
  #   image: mysteriumnetwork/myst:latest
  #   restart: always
  #   environment:
  #     - MYSTNODE_DUMMY=$MYSTNODE_API_KEY
  #   command: service --agreed-terms-and-conditions
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - 4449:4449
  #   volumes:
  #     - ./data/mysterium-node:/var/lib/mysterium-node
  #   networks:
  #     share_traffic:
  #       ipv4_address: 172.106.0.40

  Repocket:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    image: repocket/repocket:latest
    restart: always
    environment:
      - RP_EMAIL=$REPOCKET_EMAIL
      - RP_API_KEY=$REPOCKET_API_KEY
    networks:
      share_traffic:
        ipv4_address: 172.106.0.50

  TraffMonetizer:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    image: traffmonetizer/cli_v2:latest
    restart: always
    command: start accept --token ${TRAFFMONETIZER_TOKEN}
    networks:
      share_traffic:
        ipv4_address: 172.106.0.60

  dockerUI:
    image: joinsunsoft/docker.ui:latest
    restart: always
    ports:
      - 8999:8999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      share_traffic:
        ipv4_address: 172.106.0.70


networks:
    share_traffic:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16
