[program:cloudcollab]
command=/opt/cloudcollab/cloudcollab
user=root
stdout_logfile=/home/logs/cloudcollab.log
stderr_logfile=/home/logs/cloudcollab.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=2
