[program:peer2profit]
command=/opt/peer2profit/peer2profit.sh
user=root
stdout_logfile=/home/logs/peer2profit.log
stderr_logfile=/home/logs/peer2profit.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=10