[program:bitping]
command=/root/.local/bin/bitpingd
user=root
stdout_logfile=/home/logs/bitping.log
stderr_logfile=/home/logs/bitping.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=1
