[program:gaganode]
command=/opt/gaganode/gaganode.sh
user=root
stdout_logfile=/home/logs/gaganode.log
stderr_logfile=/home/logs/gaganode.log
autostart=true
startsecs=10
stopwaitsecs=30
priority=5
autorestart=false
startretries=0
