[program:honeygain]
command=/opt/honeygain/honeygain -tou-accept -email %(ENV_HONEYGAIN_EMAIL)s -pass '%(ENV_HONEYGAIN_PASSWD)s' -device %(ENV_DEVICE_NAME)s
user=root
stdout_logfile=/home/logs/honeygain.log
stderr_logfile=/home/logs/honeygain.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=6