[program:iproyalpawns]
command=/opt/iproyalpawns/pawns-cli -email=%(ENV_IPROYALPAWNS_EMAIL)s -password=%(ENV_IPROYALPAWNS_PASSWD)s -device-name=%(ENV_DEVICE_NAME)s -accept-tos
user=root
stdout_logfile=/home/logs/iproyalpawns.log
stderr_logfile=/home/logs/iproyalpawns.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=7