[program:packetstream]
command=/usr/local/bin/pslauncher
user=root
stdout_logfile=/home/logs/packetstream.log
stderr_logfile=/home/logs/packetstream.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=9