[program:proxyrack]
command=/opt/proxyrack/proxyrack.sh
user=root
stdout_logfile=/home/logs/proxyrack.log
stderr_logfile=/home/logs/proxyrack.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=12