[program:proxylite]
command=/opt/proxylite/proxylite.sh %(ENV_PROXYLITE_USER_ID)s
user=root
stdout_logfile=/home/logs/proxylite.log
stderr_logfile=/home/logs/proxylite.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=11