[program:speedshare]
command=/opt/speedshare/SpeedShareCLI connect -p %(ENV_SPEEDSHARE_TOKEN)s
user=root
stdout_logfile=/home/logs/speedshare.log
stderr_logfile=/home/logs/speedshare.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=13
