[program:spidenetwork]
command=/opt/spidenetwork/spide
user=root
stdout_logfile=/home/logs/spidenetwork.log
stderr_logfile=/home/logs/spidenetwork.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
priority=14
